// src/controllers/UserController.ts
import { Request, Response } from 'express'
import { exceptionRouter } from '../utils/utilsRequest'
import UserRepository from '../repositories/implementations/UserRepository'

class UserController {
  async createUser(req: Request, res: Response): Promise<void> {
    try {
      const userRepository = new UserRepository()
      const userData = req.body
      const { password, ...filteredUserData } = userData;
      console.log("üîç Dados recebidos para cria√ß√£o de usuario:", JSON.stringify(userData, null, 2));
      const newUser = await userRepository.createUser(filteredUserData)
      res.status(201).json({ message: 'User created', user: newUser })
    } catch (error: any) {
      console.error(`‚ùå Erro ao criar usu√°rio: `, error);
      return exceptionRouter(req, res, error)
    }
  }

  async getAllUsers(req: Request, res: Response): Promise<void> {
    try {
      const userRepository = new UserRepository()
      const users = await userRepository.getAllUsers()
      res.status(200).json({ users })
    } catch (error: any) {
      console.error(`‚ùå Erro ao buscar usu√°rios: `, error);
      return exceptionRouter(req, res, error)
    }
  }

  async getUserById(req: Request, res: Response): Promise<void> {
    const { id } = req.params
    try {
      const userRepository = new UserRepository()
      const user = await userRepository.getUserById(Number(id))
      if (!user) {
        res.status(404).json({ message: 'User not found' })
        return
      }
      res.status(200).json({ user })
    } catch (error) {
      console.error(`‚ùå Erro ao buscar usu√°rio ${id}: `, error);
      return exceptionRouter(req, res, error)
    }
  }

  async updateUser(req: Request, res: Response): Promise<void> {
    try {
      const userRepository = new UserRepository();
      const { id } = req.params;
      const userData = req.body;

      const { user, ...filteredUserData } = userData;

      console.log("üîç Dados filtrados para atualiza√ß√£o:", JSON.stringify(filteredUserData, null, 2));

      const updatedUser = await userRepository.updateUser(Number(id), filteredUserData);
      res.status(200).json({ message: "User updated", user: updatedUser });
    } catch (error) {
      console.error("‚ùå Erro ao atualizar usu√°rio:", error);
      return exceptionRouter(req, res, error);
    }
  }

  async deleteUser(req: Request, res: Response): Promise<void> {
    try {
      const userRepository = new UserRepository()
      const { id } = req.params
      await userRepository.deleteUser(Number(id))
      res.status(200).json({ message: 'User deleted' })
    } catch (error) {
      console.error(`‚ùå Erro ao deletar usu√°rio: `, error);
      return exceptionRouter(req, res, error)
    }
  }

  async findByEmail(req: Request, res: Response): Promise<void> {
    try {
      const userRepository = new UserRepository()
      const email: string = req.params.email
      const user = await userRepository.findByEmail(email)
      if (!user) {
        res.status(404).json({ message: 'User not found' })
      }
    } catch (error) {
      console.error(`‚ùå Erro ao buscar usu√°rio por email: `, error);
      return exceptionRouter(req, res, error)
    }
  }

  async searchUsers(req: Request, res: Response): Promise<void> {
    try {
      const userRepository = new UserRepository()
      const users = await userRepository.searchUsers(req.body)
      res.status(200).json(users)
    } catch (error) {
      console.error(`‚ùå Erro ao buscar usu√°rios filtrado: `, error);
      return exceptionRouter(req, res, error)
    }
  }
}

export default new UserController()
